--
CREATE TABLE MEMBER (
            MEM_NO          NUMBER(6)   PRIMARY KEY
          , MEM_CODE        NUMBER(1)   DEFAULT 1
          , ID              VARCHAR(20) NOT NULL
          , PW              VARCHAR(20) NOT NULL
          , NAME            VARCHAR(10)  NOT NULL
          , PHONE           VARCHAR(11) NOT NULL
);

--조심
--DROP TABLE MEMBER;

--테이블 확인
SELECT * FROM MEMBER ORDER BY MEM_NO ;

DELETE MEMBER WHERE NAME = '숩';

UPDATE MEMBER SET ID = 'admin' WHERE NAME = '관리자';

INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE)
            VALUES(999999, 'test', '1111', 't_admin', '0319999999');
INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE)
            VALUES(999998, 'test2', '2222', 't_user', '0319999999');


INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE, RENTAL_STATUS, RENTAL_NO)
            VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, ?, ?) ;

INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE)
            VALUES(999999, 'ADMIN', '9999', '관리자', '0319999999');
            
INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE)
            VALUES(SEQ_MEMBER_NO.NEXTVAL, 'hari1004', '1004', '이하리', '01010041004') ;


COMMIT;

SELECT ID, NAME, RENTAL_STATUS, RENTAL_NO FROM MEMBER WHERE ID = 'test';

UPDATE MEMBER SET RENTAL_STATUS = 'Y', RENTAL_NO = '00000' WHERE ID = 'test' ;

ROLLBACK;

DELETE MEMBER WHERE NAME = '숩';

CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1001 NOCACHE;

DROP SEQUENCE SEQ_MEMBER_NO;

SELECT INSTR(ID, 'admin'), ID FROM MEMBER;

SELECT * FROM MEMBER WHERE ID = 'test' AND PW = '0000' ;

SELECT ID, PW, MEM_CODE FROM MEMBER WHERE ID = 'ADMIN' AND PW = '9999';

UPDATE MEMBER SET MEM_CODE = 9 WHERE ID = 'ADMIN';