-----------------------------------------------------------------------------
--RENTAL관련

CREATE TABLE T_RENTAL(
      NO VARCHAR(10) PRIMARY KEY
    , TITLE VARCHAR(100) NOT NULL
    , AUTHOR VARCHAR(50) NOT NULL
    , PUBLISHER VARCHAR(50)
    , RENT_ID VARCHAR(20) NOT NULL
    , REN_DATE DATE NOT NULL
    , DUE_DATE DATE NOT NULL
    , OVERDUE_STATE NUMBER(10) NOT NULL
);

--테이블 확인
SELECT * FROM T_RENTAL;

COMMIT;


UPDATE T_RENTAL SET OVERDUE_STATE = TRUNC(DUE_DATE - SYSDATE) ;

UPDATE T_RENTAL SET OVERDUE_STATE = TRUNC(DUE_DATE - SYSDATE) WHERE RENT_ID = 'hari1004' ;

UPDATE T_RENTAL SET OVERDUE_STATE = TRUNC(DUE_DATE - SYSDATE) WHERE RENT_ID = 'test' ;
 

UPDATE T_RENTAL SET REN_DATE = TO_DATE('230420', 'YY/MM/DD'), DUE_DATE = TO_DATE('230423', 'YY/MM/DD') WHERE NO = '230009' ;

DELETE FROM T_RENTAL WHERE NO = '230002' ;

UPDATE T_RENTAL SET OVERDUE_STATE = ROUND(DUE_DATE - SYSDATE) WHERE RENT_ID ='hari1004' AND NO = '230009' ;


--테이블명 수정            
ALTER TABLE T_RENTAL RENAME COLUMN EXP_DATE TO DUE_DATE;

--테이블 통째로 삭제
DROP TABLE T_RENTAL;

--데이터 삽입
INSERT INTO T_RENTAL(NO, TITLE, AUTHOR, PUBLISHER, RENT_ID, REN_DATE, DUE_DATE)
            VALUES(230001, '제목', '작가', '출판사', '대여자ID', SYSDATE, SYSDATE + 3 );
            
INSERT INTO T_RENTAL(NO, TITLE, AUTHOR, PUBLISHER, RENT_ID, OVERDUE_STATE)
            VALUES(230999, '제목', '작가', '출판사', '대여자ID', (TO_DATE('20230415', 'YYYY-MM-DD')-TO_DATE('20230410', 'YYYY-MM-DD')));

INSERT INTO T_RENTAL(NO, TITLE, AUTHOR, PUBLISHER, RENT_ID)
            VALUES(230997, '제목', '작가', '출판사', '대여자ID');
            


SELECT T_RENTAL.*, ROUND(SYSDATE-DUE_DATE) AS OVERDUE FROM T_RENTAL WHERE RENT_ID = 'hari1004'; 


--날짜 테스트용
--날짜가 지나면...오늘날짜SYSDATE - DUE_DATE를 해야할듯?
SELECT  (TO_DATE('20230410', 'YYYY-MM-DD')-TO_DATE('20230415', 'YYYY-MM-DD')) AS OVERDUE_DATE, TRUNC(SYSDATE+1) FROM DUAL;

SELECT (SYSDATE-SYSDATE + 3) AS DATEE FROM DUAL;

--데이터 수정
UPDATE T_RENTAL SET REN_DATE = '20230425' WHERE NO = '230001';
UPDATE T_RENTAL SET RENT_ID = 'test' WHERE TITLE = '제목';

UPDATE T_RENTAL SET OVERDUE_STATE = DUE_DATE-SYSDATE;

--행 삭제
DELETE FROM T_RENTAL WHERE NO = '230022' ;



                    
ROLLBACK;
        



COMMIT;
